name: Docker Image CI

on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push tcp server
        uses: docker/build-push-action@v4
        with:
          context: tcpServer
          push: true
          tags: trojaj12/tcp-server:latest
      - name: Build and push udp server
        uses: docker/build-push-action@v4
        with:
          context: udpServer
          push: true
          tags: trojaj12/udp-server:latest
